In [22]:
import pandas as pd
data1=pd.read_csv("banknotes.csv")
data1.shape
X=data1[['Variance','Skewness','Curtosis','Entropy']]
#or data.drop('Class',axis=1)Here Axis 1 is column wise
y=data1['Class']
#to check any null values
X.isnull().sum()
#to check value y is there any other than 0 and 1
set(y)#return type is set not iterable


{0, 1}

In [24]:
#another to find is that y is unique\
import numpy as np
np.unique(y)#it can be iterable

array([0, 1])

In [27]:
#to check the accuracy for this purpose we are going to train test and split .
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state= 0)#random state because it is sorted so our  model dwill no know if we not give random 


In [32]:
len(X_train)

1029

In [33]:

len(X_test)#check wheter the entry are corerct

343

In [37]:
X_train.head()

Variance  Skewness  Curtosis   Entropy
662     2.9736    8.7944   -3.6359 -1.375400
512     2.6648   10.7540   -3.3994 -4.168500
1193   -3.7573   -8.2916   10.3032  0.380590
682     3.7321   -3.8840    3.3577 -0.006049
1313   -1.5078   -7.3191    7.8981  1.228900

In [39]:
y_train.head()


662     0
512     0
1193    1
682     0
1313    1
Name: Class, dtype: int64

In [41]:
#lets build classifier.Output is continuos then regression.
#tree having the Dicison tree classifier
#gini is for impurity
#check website for sklearn dicisionTree for More.

In [42]:
from sklearn.tree import DecisionTreeClassifier


In [45]:
classifier=DecisionTreeClassifier()#same as regression technique

In [48]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [49]:
#three diff characterization.wheteher clasifier is true or not.

In [53]:
y_pred=classifier.predict(X_test)#all 343 values given to test
len(y_pred)

343

In [58]:
y_pred#prdicting with the sample
y_test#this is original data

1023    1
642     0
1196    1
31      0
253     0
       ..
866     1
361     0
703     0
328     0
530     0
Name: Class, Length: 343, dtype: int64

In [60]:
y_test.head(10)

1023    1
642     0
1196    1
31      0
253     0
535     0
184     0
758     0
1308    1
914     1
Name: Class, dtype: int64

In [62]:
y_pred#first ten are applying accurate.

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,

In [63]:
#Confusion MAtrix how many entries are macthing and not matching


In [66]:
from sklearn.metrics import confusion_matrix

In [68]:
confusion_matrix(y_test,y_pred)#y_test rows #y_pred column wise 


array([[194,   1],
       [  3, 145]])

In [69]:
#0 predicted as 0 at 194 and predict as 1 for 1 time
#1 predicted as 0 at 3 and predict 1 as 145

In [72]:
339/343*100#that number of entries are matching #adv for this dicision tree is fastest

98.83381924198251

In [78]:
#we can find the accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100#first paramenter as testing data and second as predicting data

98.83381924198251

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
#Classification report genrates this kinf of output 
194,   1
3, 145
#support is the count for the test_data
#recall is indivisual class accuracy
#precison true positive rate -how many entries are true postive in predictive data
#outof 197 194 are entries are match that is why 98 percent accuracy are there
#f1 score add the precison + recall divided by 2

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       195
           1       0.99      0.98      0.99       148

    accuracy                           0.99       343
   macro avg       0.99      0.99      0.99       343
weighted avg       0.99      0.99      0.99       343



(3, 145)

In [83]:
classifier.predict([[2.9736 ,8.7944 ,-3.6359 ,-1.375400]])

array([0])

In [85]:
#d=[ 	Variance 	Skewness 	Curtosis 	Entropy]
#to input use numpy and all input of the values
d= [[2.9736 ,8.7944 ,-3.6359 ,-1.375400]]
pred=classifier.predict(d)
if pred[0]==0:
        print('Fake Note')
else :
    print('Not Fake')

Fake Note


In [87]:
#visualize the tree
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data=StringIO()
export_graphviz(classifier,out_file=dot_data,filled=True,rounded=True,special_characters=True)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('tree.png')

True